# Generated by Django 4.1.12 on 2024-01-19 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='new_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Optimistic_estimate', models.CharField(blank=True, max_length=200)),
                ('Most_likely_estimate', models.CharField(blank=True, max_length=200)),
                ('Pessimistic_estimate', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
