# Generated by Django 4.1.12 on 2024-01-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("estimates", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="new_model",
            name="label",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="new_model",
            name="original_estimate",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="new_model",
            name="priority",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="new_model",
            name="sprint_number",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="new_model",
            name="task_descrption",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="new_model",
            name="task_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
