# Generated by Django 4.1.12 on 2024-01-19 10:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("estimates", "0002_new_model_label_new_model_original_estimate_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="new_model",
            old_name="label",
            new_name="task_label",
        ),
    ]
