# Generated by Django 4.1.12 on 2024-01-23 10:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("estimates", "0003_rename_label_new_model_task_label"),
    ]

    operations = [
        migrations.RenameField(
            model_name="new_model",
            old_name="original_estimate",
            new_name="planned_estimate",
        ),
    ]
