# Generated by Django 4.1.12 on 2024-06-26 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimates', '0004_rename_original_estimate_new_model_planned_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='new_model',
            name='task_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
